#!/usr/bin/env node
// Regenerates src/font-metrics.mjs by measuring the renderer's actual font stack in headless
// Chrome (canvas measureText, regular + 600 weight). Run after changing the font stack:
//
//   node scripts/measure-font.mjs
//
// The committed table is what layout uses at runtime — this script is a dev tool, not a dependency.

import { writeFileSync, mkdtempSync, existsSync, rmSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const STACK = `"Segoe UI", -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif`;

const chrome = [
  process.env.PUPPETEER_EXECUTABLE_PATH, process.env.CHROME_PATH,
  "/opt/pw-browsers/chromium", "/usr/bin/google-chrome", "/usr/bin/google-chrome-stable",
  "/usr/bin/chromium", "/usr/bin/chromium-browser",
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
].find((p) => p && existsSync(p));
if (!chrome) { console.error("no Chrome/Chromium found"); process.exit(1); }

const chars = [...Array(95)].map((_, i) => String.fromCharCode(32 + i)).concat([..."…–—‘’“”„•·×µ°±→↳"]);
const html = `<!doctype html><meta charset="utf-8"><body><script>
  const ctx = document.createElement('canvas').getContext('2d');
  const out = { regular: {}, bold: {} };
  ctx.font = '1000px ${STACK.replace(/"/g, "&quot;")}'.replaceAll('&quot;', '"');
  for (const ch of ${JSON.stringify(chars)}) out.regular[ch] = Math.round(ctx.measureText(ch).width);
  ctx.font = '600 ' + ctx.font;
  for (const ch of ${JSON.stringify(chars)}) out.bold[ch] = Math.round(ctx.measureText(ch).width);
  document.body.textContent = JSON.stringify(out);
</script></body>`;

const dir = mkdtempSync(join(tmpdir(), "fontmeasure-"));
const page = join(dir, "measure.html");
writeFileSync(page, html);
const dom = execFileSync(chrome, ["--headless", "--no-sandbox", "--disable-gpu", "--dump-dom", "file://" + page], { encoding: "utf8" });
rmSync(dir, { recursive: true, force: true });

const m = dom.match(/\{"regular":.*\}\}/s);
if (!m) { console.error("could not extract measurements from Chrome output"); process.exit(1); }
const json = m[0].replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"');
const metrics = JSON.parse(json);

const out = `// Generated by scripts/measure-font.mjs — do not edit by hand.
// Advance widths (per mille of font size) for the renderer's font stack, measured in headless
// Chrome. "bold" is weight 600, matching every bold text the renderer emits.
export const FONT = ${JSON.stringify(metrics, null, 0)};
`;
writeFileSync(join(ROOT, "src", "font-metrics.mjs"), out);
console.log(`measured ${chars.length} glyphs × 2 weights with ${chrome} → src/font-metrics.mjs`);
